language: c

dist: bionic
sudo: false

# apparently apt addon doesn't work on bionic?
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc-multilib g++-multilib clang cmake lua5.1 luarocks ninja-build libc6-dbg:i386 tcc valgrind
  - CC= CXX= sudo luarocks install luafilesystem
  - CC= CXX= sudo luarocks install rapidjson

script: tools/ci.sh

compiler:
  - clang
  - gcc
  - scan-build

env:
  - AMALGAMATED=1
  - STANDARD=1

matrix:
  include:

    # osx build
    - os: osx
      compiler: clang
      env: "OSX=1"
      # disable before_install here to avoid apt-get on mac
      before_install:
      script:
        - cd $TRAVIS_BUILD_DIR
        - echo "Cloning JUCE:"
        - git clone https://github.com/WeAreROLI/JUCE --depth=1
        - cd JUCE
        - git checkout develop
        - JUCE_ROOT=$TRAVIS_BUILD_DIR/JUCE
        - PROJUCER_ROOT=$JUCE_ROOT/extras/Projucer/Builds/MacOSX
        - PROJUCER_APP=$PROJUCER_ROOT/build/Release/Projucer.app/Contents/MacOS/Projucer
        - echo "Building the Projucer:"
        - $PROJUCER_ROOT
        - xcodebuild -configuration Release
        - cd $TRAVIS_BUILD_DIR
        - echo "Generating Xcode project:"
        - "$PROJUCER_APP" --resave "$TRAVIS_BUILD_DIR/test/juce/mpack/mpack.jucer"
        - echo "Building test app:"
        - cd test/juce/mpack/Builds/macOS
        - xcodebuild -configuration Release
        - ls -l

    # code coverage build
    - os: linux
      compiler: gcov
      env: "STANDARD=1"
      before_install:
        - sudo apt-get update
        # these packages are needed for urllib3[secure] for SNI support for
        # coveralls integration
        - sudo apt-get install -y python-dev libffi-dev libssl-dev
        # the rest of this is copied from above
        - sudo apt-get install -y build-essential gcc-multilib g++-multilib clang cmake lua5.1 luarocks ninja-build libc6-dbg:i386 tcc valgrind
        - CC= CXX= sudo luarocks install luafilesystem
        - CC= CXX= sudo luarocks install rapidjson
